import os
import json
import shutil
from datetime import datetime
from scripts.h1_report import generate_h1_report

def h1_package():
    base = "H1_Submission"
    now = datetime.now().strftime("%Y%m%d_%H%M%S")
    folder = f"{base}_{now}"
    os.makedirs(folder, exist_ok=True)

    # 1. Generiši PDF
    generate_h1_report()

    # 2. Nađi poslednji PDF
    reports = sorted([f for f in os.listdir("reports/") if f.startswith("H1_Report")], reverse=True)
    if not reports:
        print("[!] PDF nije generisan.")
        return
    pdf_path = os.path.join("reports", reports[0])
    shutil.copy(pdf_path, os.path.join(folder, reports[0]))

    # 3. payloads.json
    try:
        shutil.copy("data/fuzz_history.json", os.path.join(folder, "payloads.json"))
    except:
        print("[!] Nema payload fajla.")

# 4. README.md
    readme = os.path.join(folder, "README.md")
    with open(readme, "w") as f:
        f.write(f"""# Security Report for HackerOne Program

**Target:** {reports[0].replace('H1_Report_', '').replace('.pdf', '')}  
**Date:** {now}  
**Generated by:** Internal automated security workflow

---

## Vulnerability Summary

Automated analysis detected signs of exploitable behavior across one or more modules:

- XSS (reflected or stored)
- SQL Injection or logical bypass
- Potential SSRF or token exposure

---

## Provided Files

- Full technical PDF report
- Raw payloads in JSON
- (Optionally: screenshots, HAR captures)

---

## Note

This package was created using internal tooling during standard fuzzing and validation.  
No commercial scanners were used. Payloads were refined and validated manually.
""")

# 5. Hidden .signature file
signature_file = os.path.join(folder, ".signature")
with open(signature_file, "w") as sig:
    sig.write(f"ShadowOps generated: {now}\n")
    sig.write(f"Origin: CUPKO-SYSTEM-AI\n")
    sig.write(f"ProofID: {hash(now) % 1000000000}\n")

# 6. ZIP paket
shutil.make_archive(folder, "zip", folder)
print(f"[✓] Paket pripremljen: {folder}.zip (sa .signature)")

if __name__ == "__main__":
    h1_package()
