import json
import os
from datetime import datetime
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas

def generate_h1_report():
    path = "data/mission_history.json"

    if not os.path.exists(path):
        print("[!] Nema fajla sa istorijom.")
        return

    with open(path) as f:
        data = json.load(f)

    if not data:
        print("[!] Fajl postoji, ali nema misija.")
        return

    last = None
    for mission in reversed(data):
        if "hackerone.com" in mission.get("target", ""):
            last = mission
            break

    if not last:
        print("[!] Nema misije za HackerOne metu.")
        return

    target = last["target"]
    timestamp = last.get("timestamp", "Nepoznat")
    results = last.get("results", {})

    pdf_path = f"reports/H1_Report_{datetime.now().strftime('%Y-%m-%d_%H-%M-%S')}.pdf"
    c = canvas.Canvas(pdf_path, pagesize=A4)
    width, height = A4
    y = height - 40
    c.setAuthor("ShadowOps-CUPKO")
    c.setTitle("Automated Security Report")
    c.setSubject("Generated by internal AI fuzzing system")
    c.setFont("Helvetica-Bold", 14)
    c.drawString(40, y, "ShadowFox: HackerOne Izveštaj")
    y -= 30
    c.setFont("Helvetica", 12)
    c.drawString(40, y, f"Cilj: {target}")
    y -= 20
    c.drawString(40, y, f"Datum: {timestamp}")
    y -= 30

    c.setFont("Helvetica-Bold", 12)
    c.drawString(40, y, "Ranjivosti detektovane:")
    y -= 20

    if isinstance(results, dict):
        for mod, res in results.items():
            c.setFont("Helvetica-Bold", 11)
            c.drawString(50, y, f"[{mod}]")
            y -= 15
            c.setFont("Helvetica", 10)
            lines = str(res).split("\n")
            for line in lines:
                c.drawString(60, y, line[:100])
                y -= 12
                if y < 50:
                    c.showPage()
                    y = height - 40
    else:
        c.drawString(50, y, "Podaci nisu pravilno sačuvani.")
        y -= 20

    c.save()
    print(f"[PDF] H1 Izveštaj sačuvan kao: {pdf_path}")

if __name__ == "__main__":
    generate_h1_report()
